# -*- coding: utf-8 -*-
{
    'name': 'NHS Trust Management — ODS Sync',
    'summary': 'Synchronise the NHS Trust register from the NHS Digital ODS portal — bulk-load, daily delta and conflict resolution',
    'version': '19.0.1.0.0',
    'category': 'Healthcare/NHS',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'license': 'LGPL-3',
    'depends': [
        'odoo_nhs_trust_management',
    ],
    'external_dependencies': {
        'python': ['requests'],
    },
    'data': [
        'security/odoo_nhs_ods_sync_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/nhs_ods_role_mapping_data.xml',
        'data/ir_cron_data.xml',
        'views/nhs_ods_config_views.xml',
        'views/nhs_ods_organisation_views.xml',
        'views/nhs_ods_role_mapping_views.xml',
        'views/nhs_ods_sync_detail_views.xml',
        'views/nhs_ods_sync_run_views.xml',
        'views/nhs_ods_sync_conflict_views.xml',
        'views/nhs_trust_views_inherit.xml',
        'wizards/nhs_ods_sync_run_wizard_views.xml',
        'wizards/nhs_ods_test_connection_wizard_views.xml',
        'wizards/nhs_ods_conflict_resolve_wizard_views.xml',
        'views/nhs_ods_menus.xml',
    ],
    'application': False,
    'installable': True,
    'auto_install': False,
}
