# -*- coding: utf-8 -*-
{
    'name': 'NHS Trust Management — UK Regions Extension',
    'summary': 'Extends the NHS Trust register to NHS Wales (7 LHBs) and HSC Northern Ireland (5 HSC Trusts + NIAS)',
    'version': '19.0.1.0.0',
    'category': 'Healthcare/NHS',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'license': 'LGPL-3',
    'depends': ['odoo_nhs_trust_management'],
    'data': [
        'security/odoo_nhs_uk_regions_security.xml',
        'security/ir.model.access.csv',
        'data/nhs_region_data.xml',
        'data/nhs_trust_type_data.xml',
        'data/nhs_welsh_lhb_data.xml',
        'data/nhs_trust_data_wales.xml',
        'data/nhs_trust_data_ni.xml',
        'views/nhs_welsh_lhb_views.xml',
        'views/nhs_trust_views_inherit.xml',
        'views/res_users_views_inherit.xml',
        'views/nhs_trust_menus_inherit.xml',
    ],
    'application': False,
    'installable': True,
    'auto_install': False,
}
