from . import hospital_patient
from . import hospital_appointment
from . import hospital_doctor
from . import hospital_department
from . import hospital_consultation
from . import hospital_prescription
from . import hospital_medicine
from . import hospital_lab
from . import hospital_ward
from . import hospital_insurance
from . import hospital_surgery
from . import hospital_billing
from . import account_move