{
    'name': 'NHS Incident & Risk Management',
    'summary': 'Datix-class incident reporting, PSIRF investigations, Duty of '
               'Candour, RIDDOR, CQC notifications and a 5x5 risk register — '
               'for NHS trusts, GP practices, care homes and all CQC providers',
    'version': '19.0.1.0.0',
    'category': 'Healthcare/NHS',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'license': 'OPL-1',
    'price': 0,
    'currency': 'EUR',
    'depends': ['base', 'mail', 'portal'],
    'data': [
        'security/nhs_security.xml',
        'security/ir.model.access.csv',
        'data/nhs_sequence_data.xml',
        'data/nhs_matrix_data.xml',
        'data/nhs_holiday_data.xml',
        'data/nhs_terminology_data.xml',
        'data/nhs_category_data.xml',
        'data/nhs_notification_rule_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'views/nhs_location_views.xml',
        'views/nhs_incident_views.xml',
        'views/nhs_investigation_views.xml',
        'views/nhs_statutory_views.xml',
        'views/nhs_action_views.xml',
        'views/nhs_risk_views.xml',
        'views/nhs_config_views.xml',
        'views/nhs_dashboard_views.xml',
        'views/public_report_templates.xml',
        'report/nhs_incident_reports.xml',
        'report/nhs_risk_reports.xml',
        'report/nhs_board_pack_report.xml',
        'wizards/nhs_triage_wizard_views.xml',
        'wizards/nhs_riddor_wizard_views.xml',
        'wizards/nhs_risk_escalate_wizard_views.xml',
        'wizards/nhs_lfpse_export_wizard_views.xml',
        'wizards/nhs_risk_review_wizard_views.xml',
        'wizards/nhs_provider_setup_wizard_views.xml',
        'views/nhs_menus.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'odoo_nhs_incident_risk/static/src/js/public_form.js',
            'odoo_nhs_incident_risk/static/src/css/public_form.css',
        ],
    },
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
}
