# -*- coding: utf-8 -*-
from . import fitness_member
from . import fitness_membership_plan
from . import fitness_subscription
from . import fitness_trainer
from . import fitness_attendance
from . import fitness_class
from . import fitness_class_schedule
from . import fitness_class_booking
from . import fitness_equipment
from . import fitness_equipment_maintenance
from . import fitness_payment
from . import account_move
from . import account_payment
from . import fitness_training_session
from . import fitness_trainer_schedule
from . import fitness_workout_plan
from . import fitness_diet_plan
from . import fitness_member_progress
from . import fitness_exercise_library
from . import fitness_workout_log
from . import fitness_food_item
from . import fitness_meal_log
from . import fitness_meditation_session
from . import fitness_sleep_log
from . import fitness_social_post
from . import fitness_social_kudos
from . import fitness_challenge
from . import fitness_exercise_library
from . import fitness_workout_log
